# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: broker-deployment
serviceName: broker
appLabel: broker
appName: broker

replicaCount: 2

image:
  repository: hcorptech/broker
  tag: 0.0.1

containerPort: 8085

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

appname_enabled: true
profile_enabled: true
discovery_enable: true
mongo_host_enable: true
jwt_enable: false
