# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: discovery-deployment
serviceName: discovery
appLabel: discovery
appName: discovery

replicaCount: 1

image:
  repository: hcorptech/discoveryserver
  tag: 0.0.1

containerPort: 8761

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"  # Increased from 256Mi
  limits:
    cpu: "500m"
    memory: "1Gi"    # Increased from 512Mi to 1GB

service:
  type: LoadBalancer
  port: 8761
  targetPort: 8761

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: false